[package]
name = "wayland-wire"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
byteorder = "1.5"
quick-xml = "0.31"
libc = "0.2"
waybroker-common.workspace = true

[dev-dependencies]
tempfile = "3.8"
